/**
 *
 * @license
 * Copyright (C) 2016 Joseph Roque
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author Joseph Roque
 * @file Buildings.js
 * @description Provides names and images of all buildings on the University of Ottawa campus.
 *
 */
'use strict';

/* eslint-disable */

module.exports = [

  {
    shorthand: '90U',
    image: require('../images/buildings/full/90U.jpg'),
    thumbnail: require('../images/buildings/thumbnail/90U.jpg'),
    name_en: '90 University',
    name_fr: '90 Université',
    location: {
      latitude: 45.422398,
      longitude: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'ARC',
    image: require('../images/buildings/full/ARC.jpg'),
    thumbnail: require('../images/buildings/thumbnail/ARC.jpg'),
    name_en: 'Advanced Research Centre',
    name_fr: 'Complexe de recherche avancée',
    location: {
      latitude: 45.420723,
      longitude: -75.678712,
    },
    address_en: '25 Templeton Street',
    address_fr: '25, rue Templeton',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'ATK',
    image: require('../images/buildings/full/ATK.jpg'),
    thumbnail: require('../images/buildings/thumbnail/ATK.jpg'),
    name_en: 'Alex Trebek Alumni Hall',
    name_fr: 'Pavillon des diplômés Alex-Trebek',
    location: {
      latitude: 45.425135,
      longitude: -75.686424,
    },
    address_en: '155 Séraphin-Marion Private',
    address_fr: '155, rue Séraphin-Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'AWHC',
    image: require('../images/buildings/full/AWHC.jpg'),
    thumbnail: require('../images/buildings/thumbnail/AWHC.jpg'),
    name_en: 'Academic Writing Help Centre',
    name_fr: 'Centre d’aide à la rédaction des travaux universitaires',
    location: {
      latitude: 45.421908,
      longitude: -75.684414,
    },
    address_en: '110 University Private',
    address_fr: '110, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'BRS',
    image: require('../images/buildings/full/BRS.jpg'),
    thumbnail: require('../images/buildings/thumbnail/BRS.jpg'),
    name_en: 'Brooks Residence',
    name_fr: 'Résidence Brooks',
    location: {
      latitude: 45.423329,
      longitude: -75.681810,
    },
    address_en: '100 Thomas More Private, 622-638 King Edward Avenue',
    address_fr: '100, rue Thomas More; 622-638, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'BSC',
    image: require('../images/buildings/full/BSC.jpg'),
    thumbnail: require('../images/buildings/thumbnail/BSC.jpg'),
    name_en: 'Biosciences Complex',
    name_fr: 'Complexe des biosciences',
    location: {
      latitude: 45.421329,
      longitude: -75.681500,
    },
    address_en: '30 Marie-Curie Private',
    address_fr: '30, privé Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'CBY',
    image: require('../images/buildings/full/CBY.jpg'),
    thumbnail: require('../images/buildings/thumbnail/CBY.jpg'),
    name_en: 'Colonel By Hall',
    name_fr: 'Pavillon Colonel By',
    location: {
      latitude: 45.419883,
      longitude: -75.679473,
    },
    address_en: '161 Louis-Pasteur Private',
    address_fr: '161, privé Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'CRG',
    image: require('../images/buildings/full/CRG.jpg'),
    thumbnail: require('../images/buildings/thumbnail/CRG.jpg'),
    name: 'CAREG',
    location: {
      latitude: 45.421134,
      longitude: -75.682059,
    },
    address_en: '20 Marie-Curie Private',
    address_fr: '20, privé Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'CTE',
    image: require('../images/buildings/full/CTE.jpg'),
    thumbnail: require('../images/buildings/thumbnail/CTE.jpg'),
    name_en: 'Power Plant',
    name_fr: 'Centrale thermique',
    location: {
      latitude: 45.421031,
      longitude: -75.679920,
    },
    address_en: '720 King Edward Avenue',
    address_fr: '720, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'DMS',
    image: require('../images/buildings/full/DMS.jpg'),
    thumbnail: require('../images/buildings/thumbnail/DMS.jpg'),
    name_en: 'Desmarais Hall',
    name_fr: 'Pavillon Desmarais',
    location: {
      latitude: 45.423884,
      longitude: -75.687202,
    },
    address_en: '55 Laurier Avenue East',
    address_fr: '55, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'DRO',
    image: require('../images/buildings/full/DRO.jpg'),
    thumbnail: require('../images/buildings/thumbnail/DRO.jpg'),
    name_en: 'D\'Iorio Hall',
    name_fr: 'Pavillon D\'Iorio',
    location: {
      latitude: 45.420956,
      longitude: -75.681306,
    },
    address_en: '10 Marie-Curie Private',
    address_fr: '10, privé Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'EMBA',
    image: require('../images/buildings/full/EMBA.jpg'),
    thumbnail: require('../images/buildings/thumbnail/EMBA.jpg'),
    name: 'Executive MBA Program',
    location: {
      latitude: 45.421237,
      longitude: -75.698082,
    },
    address_en: '45 O\'Connor Street',
    address_fr: '45, rue O\'Connor',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'FRL',
    image: require('../images/buildings/full/FRL.jpg'),
    thumbnail: require('../images/buildings/thumbnail/FRL.jpg'),
    name_en: 'Friel Residence',
    name_fr: 'Résidence Friel',
    location: {
      latitude: 45.430552,
      longitude: -75.682910,
    },
    address_en: '240 Friel St',
    address_fr: '240, rue Friel',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'FSS',
    image: require('../images/buildings/full/FSS.jpg'),
    thumbnail: require('../images/buildings/thumbnail/FSS.jpg'),
    name_en: 'Social Sciences Building',
    name_fr: 'Pavillon des Sciences sociales',
    location: {
      latitude: 45.421541,
      longitude: -75.683783,
    },
    address_en: '120 University Private',
    address_fr: '120, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'FTX',
    image: require('../images/buildings/full/FTX.jpg'),
    thumbnail: require('../images/buildings/thumbnail/FTX.jpg'),
    name_en: 'Fauteux Hall',
    name_fr: 'Pavillon Fauteux',
    location: {
      latitude: 45.423748,
      longitude: -75.682569,
    },
    address_en: '57 Louis-Pasteur Private',
    address_fr: '57, privé Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'GNN',
    image: require('../images/buildings/full/GNN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/GNN.jpg'),
    name_en: 'Gendron Hall',
    name_fr: 'Pavillon Gendron',
    location: {
      latitude: 45.421329,
      longitude: -75.681500,
    },
    address_en: '30 Marie-Curie Private',
    address_fr: '30, privé Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'GSD',
    image: require('../images/buildings/full/GSD.jpg'),
    thumbnail: require('../images/buildings/thumbnail/GSD.jpg'),
    name_en: 'GSAED Grad House',
    name_fr: 'Maison des Étudians Diplômés GSAED',
    location: {
      latitude: 45.423824,
      longitude: -75.684096,
    },
    address_en: '601 Cumberland Street',
    address_fr: '601, rue Cumberland',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'HGN',
    image: require('../images/buildings/full/HGN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/HGN.jpg'),
    name_en: 'Hagen Hall',
    name_fr: 'Pavillon Hagen',
    location: {
      latitude: 45.425482,
      longitude: -75.685541,
    },
    address_en: '115 Séraphin Marion Private',
    address_fr: '115, rue Séraphin Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'HNN',
    image: require('../images/buildings/full/HNN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/HNN.jpg'),
    name_en: 'Henderson Residence',
    name_fr: 'Résidence Henderson',
    location: {
      latitude: 45.4213294,
      longitude: -75.6805316,
    },
    address_en: '202 Henderson Avenue',
    address_fr: '202, avenue Henderson',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'HSY',
    image: require('../images/buildings/full/HSY.jpg'),
    thumbnail: require('../images/buildings/thumbnail/HSY.jpg'),
    name_en: 'Hyman Soloway Residence',
    name_fr: 'Résidence Hyman Soloway',
    location: {
      latitude: 45.425136,
      longitude: -75.684281,
    },
    address_en: '157 Laurier Avenue East',
    address_fr: '157, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'KEB',
    image: require('../images/buildings/full/KEB.jpg'),
    thumbnail: require('../images/buildings/thumbnail/KEB.jpg'),
    name_en: 'Fulcrum, OPIRG',
    name_fr: 'Fulcrum, GRIPO',
    location: {
      latitude: 45.423211,
      longitude: -75.680906,
    },
    address_en: '631 King Edward Avenue',
    address_fr: '631, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'KED',
    image: require('../images/buildings/full/KED.jpg'),
    thumbnail: require('../images/buildings/thumbnail/KED.jpg'),
    name_en: 'Department of Mathematics and Statistics',
    name_fr: 'Département de mathématiques et statistique',
    location: {
      latitude: 45.424441,
      longitude: -75.681918,
    },
    address_en: '585 King Edward Avenue',
    address_fr: '585, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LBC',
    image: require('../images/buildings/full/LBC.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LBC.jpg'),
    name_en: 'Leblanc Residence',
    name_fr: 'Résidence Leblanc',
    location: {
      latitude: 45.423335,
      longitude: -75.682451,
    },
    address_en: '45 Louis-Pasteur Private',
    address_fr: '45, privé Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LEES',
    image: require('../images/buildings/full/LEES.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LEES.jpg'),
    name: '200 Lees',
    location: {
      latitude: 45.416261,
      longitude: -75.669485,
    },
    address_en: '200 Lees Avenu',
    address_fr: '200, avenue Lees',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LMX',
    image: require('../images/buildings/full/LMX.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LMX.jpg'),
    name_en: 'Lamoureux Hall',
    name_fr: 'Pavillon Lamoureux',
    location: {
      latitude: 45.421521,
      longitude: -75.682128,
    },
    address_en: '145 Jean-Jacques-Lussier Private',
    address_fr: '145, privé Jean-Jacques-Lussier',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LPR',
    image: require('../images/buildings/full/LPR.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LPR.jpg'),
    name_en: 'Louis-Pasteur',
    name_fr: 'Louis-Pasteur',
    location: {
      latitude: 45.421136,
      longitude: -75.680287,
    },
    address_en: '141 Louis-Pasteur Private',
    address_fr: '141, privé Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LRR',
    image: require('../images/buildings/full/LRR.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LRR.jpg'),
    name_en: '100 Laurier',
    name_fr: '100 Laurier',
    location: {
      latitude: 45.424247,
      longitude: -75.685087,
    },
    address_en: '100 Laurier Avenue East',
    address_fr: '100, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MCE',
    image: require('../images/buildings/full/MCE.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MCE.jpg'),
    name: '100 Marie-Curie',
    location: {
      latitude: 45.421752,
      longitude: -75.680984,
    },
    address_en: '100 Marie-Curie Private',
    address_fr: '100, privé Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MHN',
    image: require('../images/buildings/full/MHN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MHN.jpg'),
    name_en: 'Hamelin Hall',
    name_fr: 'Pavillon Hamelin',
    location: {
      latitude: 45.423807,
      longitude: -75.685800,
    },
    address_en: '70 Laurier Avenue East',
    address_fr: '70, avenue Laurier est',
    facilities: [
      'food',
      'printer',
      'library',
      'parking',
    ],
    rooms: [
      {
        name: '02',
        type: 'library',
        alt_name_en: 'Julien Couture Resource Centre',
        alt_name_fr: 'Centre de ressources Julien-Couture',
      },
      { name: '03' },
      { name: '04', type: 'bath_women' },
      { name: '05' },
      { name: '06', type: 'bath_men' },
      { name: '07' },
      { name: '08' },
      { name: '09' },
      { name: '010' },
      { name: '012' },
      { name: '013' },
      { name: '015' },
      { name: '016' },
      { name: '017' },
      { name: '018' },
      { name: '019' },
      {
        name: '020',
        type: 'lab_res',
        alt_name_en: 'J.A. Bombardier Foundation Room',
        alt_name_fr: 'Salle Fondation J.A. Bombardier',
      },
      { name: '021' },
      { name: '022' },
      { name: '023' },
      { name: '024' },
      { name: '025' },
      { name: '026' },
      { name: '027' },
      { name: '028' },
      { name: '029' },
      {
        name: '030',
        type: 'cafe',
        alt_name: 'GO Café',
      },
      { name: '033', type: 'class', },
      { name: '101' },
      { name: '102' },
      { name: '103' },
      { name: '104' },
      { name: '105' },
      { name: '106' },
      { name: '107' },
      { name: '108' },
      { name: '109' },
      { name: '110' },
      {
        name: '111',
        type: 'service',
        alt_name_en: 'Graduate Student Association',
        alt_name_fr: 'Association des étudiants diplômés',
      },
      { name: '112' },
      { name: '114' },
      { name: '115' },
      {
        name: '117',
        alt_name_en: 'Language Testing Services',
        alt_name_fr: 'Services d\'evaluation linguistique',
      },
      { name: '118' },
      { name: '120', type: 'bath_men' },
      { name: '121' },
      { name: '122' },
      { name: '123' },
      { name: '124', type: 'bath_women' },
      { name: '125' },
      { name: '126' },
      { name: '127' },
      {
        name: '130',
        alt_name_en: 'OLBI',
        alt_name_fr: 'ILOB',
      },
      { name: '131' },
      { name: '133' },
      { name: '134' },
      { name: '135' },
      { name: '136' },
      { name: '137' },
      { name: '138' },
      { name: '139' },
      { name: '140', type: 'test', },
      { name: '141' },
      { name: '142', type: 'kitchen', },
      { name: '143' },
      { name: '144' },
      { name: '145', type: 'meet', },
      { name: '201' },
      { name: '202' },
      { name: '203' },
      { name: '204' },
      { name: '205' },
      { name: '206' },
      { name: '207' },
      { name: '208' },
      { name: '210' },
      { name: '211' },
      { name: '212' },
      { name: '213' },
      {
        name: '215',
        type: 'seminar',
        alt_name_en: 'Scotiabank Room',
        alt_name_fr: 'Salle Banque Scotia',
      },
      { name: '216' },
      { name: '217' },
      { name: '218' },
      { name: '219' },
      { name: '220' },
      { name: '221' },
      { name: '222' },
      { name: '223' },
      { name: '224' },
      { name: '225' },
      { name: '226', type: 'bath_men' },
      { name: '227' },
      { name: '228' },
      { name: '229' },
      { name: '230', type: 'bath_women' },
      { name: '231' },
      { name: '232' },
      { name: '233', type: 'kitchen', },
      {
        name: '234',
        type: 'service',
        alt_name_en: 'Modern Languages and Literature Secretariat',
        alt_name_fr: 'Sécretariat des langues et littératures modernes',
      },
      { name: '235' },
      { name: '236' },
      { name: '237' },
      { name: '238' },
      { name: '239' },
      { name: '240' },
      { name: '241' },
      { name: '242' },
      { name: '243' },
      { name: '244' },
      { name: '245' },
      { name: '246', type: 'meet', },
      { name: '247' },
      { name: '248' },
      { name: '249' },
      { name: '250' },
      { name: '251' },
      { name: '252' },
      { name: '253' },
      { name: '257', type: 'class', },
      { name: '301', type: 'meet', },
      { name: '302' },
      { name: '303' },
      { name: '304' },
      { name: '305' },
      { name: '306' },
      { name: '307' },
      { name: '308' },
      { name: '309' },
      { name: '310' },
      { name: '311' },
      { name: '313' },
      { name: '314' },
      { name: '315' },
      { name: '316' },
      {
        name: '318',
        type: 'seminar',
        alt_name_en: 'Metropolitan Life Room',
        alt_name_fr: 'Salle La Métropolitaine',
      },
      { name: '319' },
      { name: '320' },
      {
        name: '321',
        type: 'service',
        alt_name: 'Undergraduate English Students\' Association',
      },
      { name: '322' },
      { name: '323' },
      { name: '324' },
      { name: '325' },
      { name: '326' },
      { name: '327' },
      { name: '328' },
      { name: '329' },
      { name: '330' },
      { name: '331', type: 'bath_men' },
      { name: '332' },
      { name: '333', type: 'bath_women' },
      { name: '334' },
      { name: '336' },
      { name: '337' },
      {
        name: '338',
        alt_name_en: 'English Secretariat',
        alt_name_fr: 'Sécretariat des anglais',
      },
      { name: '339' },
      { name: '340' },
      { name: '341' },
      { name: '342' },
      { name: '343' },
      { name: '344' },
      { name: '345' },
      { name: '346' },
      { name: '347' },
      { name: '348' },
      { name: '349' },
      { name: '350', type: 'seminar', },
      { name: '351' },
      { name: '352' },
      { name: '353' },
      { name: '354' },
      { name: '355' },
      { name: '356' },
      {
        name: '401',
        alt_name_en: 'Linguistics, Translation and Interpretation Secretariat',
        alt_name_fr: 'Sécretariat des linguistique, traduction et interprétation',
      },
      { name: '402' },
      { name: '403' },
      { name: '404' },
      { name: '405' },
      { name: '406' },
      { name: '407' },
      { name: '408' },
      { name: '409' },
      { name: '410' },
      { name: '411' },
      { name: '412' },
      { name: '413' },
      { name: '415' },
      { name: '416' },
      { name: '417' },
      { name: '418' },
      {
        name: '420',
        type: 'seminar',
        alt_name_en: 'CIBC Room',
        alt_name_fr: 'Salle CIBC',
      },
      { name: '421' },
      { name: '422' },
      { name: '423' },
      { name: '424' },
      { name: '425' },
      { name: '426' },
      { name: '428' },
      { name: '429' },
      { name: '430' },
      { name: '432' },
      { name: '433' },
      { name: '434' },
      { name: '435' },
      {
        name: '436',
        type: 'meet',
        alt_name_en: 'Salon Monet Room',
        alt_name_fr: 'Salle Salon Monet',
      },
      { name: '437' },
      { name: '438' },
      { name: '439' },
      { name: '440' },
      { name: '441' },
      { name: '442' },
      { name: '443' },
      { name: '444' },
      { name: '445' },
      { name: '446' },
      { name: '447' },
      { name: '448' },
      { name: '449' },
      { name: '450' },
      { name: '451' },
      { name: '452' },
      {
        name: '501',
        type: 'service',
        alt_name_en: 'Digital Humanities',
        alt_name_fr: 'Sciences humaines numériques',
      },
      { name: '502' },
      { name: '503' },
      { name: '504' },
      { name: '505' },
      {
        name: '506',
        type: 'meet',
        alt_name_en: 'Brian Harris Room',
        alt_name_fr: 'Salle Brian Harris',
      },
      { name: '507' },
      { name: '509', type: 'meet', },
      { name: '511' },
      { name: '513', type: 'bath_uni', },
      { name: '515' },
      { name: '516' },
      { name: '517' },
      { name: '518' },
      { name: '519' },
      { name: '520' },
      { name: '521' },
      { name: '522' },
      { name: '523', type: 'seminar', },
      { name: '524' },
      { name: '525' },
      {
        name: '526',
        type: 'service',
        alt_name_en: 'Faculty of Arts Writing Centre',
        alt_name_fr: 'Centre d\'écriture de la faculté des arts',
      },
      { name: '527' },
      { name: '528' },
      { name: '529' },
      { name: '530' },
      { name: '531' },
    ],
  },

  {
    shorthand: 'MNN',
    image: require('../images/buildings/full/MNN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MNN.jpg'),
    name: '45 Mann',
    location: {
      latitude: 45.419971,
      longitude: -75.676069,
    },
    address_en: '45 Mann Avenue',
    address_fr: '45, avenue Mann',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MNO',
    image: require('../images/buildings/full/MNO.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MNO.jpg'),
    name_en: 'Minto Sports Complex',
    name_fr: 'Complexe sportif Minto',
    location: {
      latitude: 45.419746,
      longitude: -75.677470,
    },
    address_en: '801 King Edward Avenue',
    address_fr: '801, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MNT',
    image: require('../images/buildings/full/MNT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MNT.jpg'),
    name_en: 'Montpetit Hall',
    name_fr: 'Pavillon Montpetit',
    location: {
      latitude: 45.422627,
      longitude: -75.682164,
    },
    address_en: '125 University Private',
    address_fr: '125, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRD',
    image: require('../images/buildings/full/MRD.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MRD.jpg'),
    name_en: 'Marchand Residence',
    name_fr: 'Résidence Marchand',
    location: {
      latitude: 45.422398,
      longitude: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRN',
    image: require('../images/buildings/full/MRN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MRN.jpg'),
    name_en: 'Marion Hall',
    name_fr: 'Pavillon Marion',
    location: {
      latitude: 45.420643,
      longitude: -75.680979,
    },
    address_en: '140 Louis-Pasteur Private',
    address_fr: '140, privé Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRT',
    image: require('../images/buildings/full/MRT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MRT.jpg'),
    name_en: 'Morisset Hall',
    name_fr: 'Pavillon Morisset',
    location: {
      latitude: 45.423232,
      longitude: -75.684163,
    },
    address_en: '65 University Private',
    address_fr: '65, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'NCL',
    image: require('../images/buildings/full/NCL.jpg'),
    thumbnail: require('../images/buildings/thumbnail/NCL.jpg'),
    name: '1 Nicholas',
    location: {
      latitude: 45.426515,
      longitude: -75.690035,
    },
    address_en: '1 Nicholas Street',
    address_fr: '1, rue Nicholas',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'ODL',
    image: require('../images/buildings/full/ODL.jpg'),
    thumbnail: require('../images/buildings/thumbnail/ODL.jpg'),
    name_en: 'Odell Hous',
    name_fr: 'Maison Odell',
    location: {
      latitude: 45.422696,
      longitude: -75.686121,
    },
    address_en: '180 Waller Street',
    address_fr: '180, rue Waller',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'PRZ',
    image: require('../images/buildings/full/PRZ.jpg'),
    thumbnail: require('../images/buildings/thumbnail/PRZ.jpg'),
    name_en: 'Pérez Hall',
    name_fr: 'Pavillon Pérez',
    location: {
      latitude: 45.423789,
      longitude: -75.684767,
    },
    address_en: '50 University Private',
    address_fr: '50, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'RDU',
    image: require('../images/buildings/full/RDU.jpg'),
    thumbnail: require('../images/buildings/thumbnail/RDU.jpg'),
    name_en: 'Rideau Residence',
    name_fr: 'Résidence Rideau',
    location: {
      latitude: 45.428705,
      longitude: -75.685829,
    },
    address_en: '290 Rideau Street',
    address_fr: '290, rue Rideau',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'RGN',
    image: require('../images/buildings/full/RGN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/RGN.jpg'),
    name_en: 'Roger Guindon Hall',
    name_fr: 'Pavillon Roger Guindon',
    location: {
      latitude: 45.402476,
      longitude: -75.650102,
    },
    address_en: '451 Smyth Road',
    address_fr: '451, rue Smyth',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'La Rotonde',
    image: require('../images/buildings/full/LaRotonde.jpg'),
    thumbnail: require('../images/buildings/thumbnail/LaRotonde.jpg'),
    name: 'La Rotonde',
    location: {
      latitude: 45.424038,
      longitude: -75.680850,
    },
    address_en: '109 Osgoode Street',
    address_fr: '109, rue Osgoode',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SCR',
    image: require('../images/buildings/full/SCR.jpg'),
    thumbnail: require('../images/buildings/thumbnail/SCR.jpg'),
    name: 'Sacré-Coeur',
    location: {
      latitude: 45.423824,
      longitude: -75.684096,
    },
    address_en: '591 Cumberland Street',
    address_fr: '591, rue Cumberland',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SCS',
    image: require('../images/buildings/full/MNO.jpg'),
    thumbnail: require('../images/buildings/thumbnail/MNO.jpg'),
    name_en: 'Minto Sports Complex',
    name_fr: 'Complexe sportif Minto',
    location: {
      latitude: 45.419746,
      longitude: -75.677470,
    },
    address_en: '801 King Edward Avenue',
    address_fr: '801, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SMD',
    image: require('../images/buildings/full/SMD.jpg'),
    thumbnail: require('../images/buildings/thumbnail/SMD.jpg'),
    name_en: 'Simard Hall',
    name_fr: 'Pavillon Simard',
    location: {
      latitude: 45.423215,
      longitude: -75.685737,
    },
    address_en: '60 University Private',
    address_fr: '60, privé University',
    facilities: [
      'food',
      'printer',
    ],
    rooms: [

      {
        name: '003',
        type: 'lab_res',
        alt_name_en: 'Physical Geography Laboratory',
        alt_name_fr: 'Laboratoire de géographie physique',
      },
      { name: '004', type: 'lab_res' },
      {
        name: '005',
        type: 'lab_res',
        alt_name_en: 'Physical Geography Laboratory',
        alt_name_fr: 'Laboratoire de géographie physique',
      },
      { name: '006' },
      { name: '007' },
      { name: '009' },
      { name: '0010' },
      { name: '0011' },
      { name: '0012' },
      { name: '0013' },
      { name: '0014' },
      { name: '0015' },
      { name: '0016' },
      { name: '0017', type: 'bath_men' },
      { name: '0019', type: 'bath_women' },
      { name: '0020' },
      {
        name: '0021A',
        type: 'lab_res',
        alt_name_en: 'Laboratory for Environment, Society and Policy',
        alt_name_fr: 'Laboratoire sur l\'environnement, la société et la politique publique',
      },
      { name: '0021B' },
      {
        name: '0021C',
        type: 'lab_res',
        alt_name_en: 'Laboratory for Interactive Research on Environmental Change and Public Policy',
        alt_name_fr: 'Laboratoire interactif de recherche sur les changements environnementaux et politiques publiques',
      },
      { name: '0025' },
      { name: '0026' },
      { name: '0027' },
      { name: '0028' },
      { name: '0030' },
      { name: '0031' },
      { name: '0034' },
      { name: '0035' },
      { name: '0036' },
      {
        name: '0029',
        type: 'cafe',
        alt_name: 'Café Alternatif',
      },
      { name: '03', type: 'kitchen' },
      { name: '05' },
      { name: '06' },
      { name: '07' },
      { name: '08' },
      { name: '09' },
      { name: '010' },
      { name: '012' },
      { name: '013' },
      { name: '014' },
      { name: '015' },
      { name: '016' },
      { name: '017' },
      { name: '018' },
      { name: '019' },
      { name: '020' },
      { name: '021' },
      { name: '023' },
      { name: '024', type: 'bath_men' },
      { name: '025' },
      { name: '026', type: 'bath_women' },
      { name: '027' },
      { name: '028' },
      { name: '029' },
      { name: '030' },
      { name: '031' },
      { name: '032' },
      { name: '033' },
      {
        name: '036',
        type: 'lab_res',
        alt_name_en: 'Health and Environment Analysis Laboratory',
        alt_name_fr: 'Laboratoire d\'analyse en environnement et santé',
      },
      { name: '037' },
      { name: '038', type: 'comp' },
      {
        name: '039',
        type: 'lab_teach',
        alt_name_en: 'G.I.S Teaching Laboratory',
        alt_name_fr: 'Laboratoires d\'enseignement S.I.G.',
      },
      { name: '040' },
      { name: '041', type: 'class' },
      {
        name: '042',
        type: 'lab_res',
        alt_name_en: 'Laboratory for Applied Geomatics and GIS Science',
        alt_name_fr: 'Laboratoire pour la géomatique appliquée et la science des SIG',
      },
      {
        name: '043',
        type: 'lab_res',
        alt_name_en: 'Laboratory for Cryospheric Research',
        alt_name_fr: 'Laboratoire de recherche cryosphérique',
      },
      { name: '044' },
      { name: '045' },
      { name: '046', type: 'meet' },
      {
        name: '047',
        alt_name_en: 'Geography Secretariat',
        alt_name_fr: 'Géographie Secrétariat',
      },
      { name: '102C' },
      { name: '102D', type: 'kitchen' },
      { name: '103' },
      { name: '104' },
      { name: '106' },
      { name: '107' },
      { name: '108' },
      { name: '109' },
      { name: '110' },
      { name: '112' },
      { name: '113' },
      { name: '114' },
      { name: '115' },
      { name: '116' },
      { name: '117' },
      { name: '120', type: 'bath_women' },
      { name: '121' },
      { name: '122' },
      { name: '123', type: 'meet' },
      { name: '125', type: 'meet' },
      {
        name: '125B',
        type: 'service',
        alt_name_en: 'Student Mentoring Centre',
        alt_name_fr: 'Centre de mentorat',
      },
      { name: '126', type: 'bath_men' },
      {
        name: '127',
        type: 'service',
        alt_name_en: 'Undergraduate Studies Office',
        alt_name_fr: 'Bureau du 1er cycle',
      },
      {
        name: '128',
        type: 'service',
        alt_name_en: 'Faculty of Arts Academic Services',
        alt_name_fr: 'Faculté des arts Services scolaires',
      },
      { name: '129' },
      {
        name: '202',
        alt_name: 'Départment de français Secrétariat',
      },
      { name: '204' },
      { name: '205' },
      { name: '206' },
      { name: '207' },
      { name: '208' },
      { name: '209' },
      { name: '211' },
      { name: '212' },
      { name: '213' },
      { name: '214' },
      { name: '215' },
      { name: '216' },
      { name: '217' },
      { name: '219', type: 'bath_men' },
      { name: '220' },
      { name: '221', type: 'class' },
      { name: '222', type: 'class' },
      { name: '224', type: 'class' },
      { name: '225', type: 'bath_women' },
      { name: '226', type: 'class' },
      { name: '227', type: 'class' },
      { name: '228' },
      {
        name: '229',
        type: 'lab_teach',
        alt_name: 'Laboratoire Polyphonies du français',
      },
      { name: '302' },
      { name: '304' },
      { name: '305' },
      { name: '306' },
      { name: '307' },
      { name: '308' },
      { name: '309' },
      { name: '311' },
      { name: '312' },
      { name: '313' },
      { name: '314' },
      { name: '315' },
      { name: '316', type: 'kitchen' },
      { name: '317' },
      { name: '319' },
      { name: '320', type: 'bath_women' },
      {
        name: '321',
        type: 'service',
        alt_name_en: 'Student Mentoring Centre',
        alt_name_fr: 'Centre de mentorat',
      },
      {
        name: '322',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      {
        name: '324',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      {
        name: '326',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      {
        name: '327',
        alt_name: 'Department of English',
      },
      {
        name: '328',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      { name: '329', type: 'bath_men' },
      { name: '330', type: 'class' },
      { name: '331' },
      {
        name: '332',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      {
        name: '333',
        type: 'lab_teach',
        alt_name_en: 'Language Laboratory',
        alt_name_fr: 'Laboratoire de langue',
      },
      { name: '334' },
      { name: '402', type: 'class' },
      { name: '404' },
      { name: '405' },
      { name: '406' },
      { name: '407' },
      { name: '408' },
      { name: '409' },
      { name: '411' },
      { name: '412' },
      { name: '413' },
      { name: '414' },
      { name: '415' },
      { name: '416' },
      { name: '417' },
      { name: '419' },
      { name: '420', type: 'bath_women' },
      { name: '421' },
      { name: '422', type: 'class' },
      { name: '423', type: 'class' },
      { name: '425', type: 'class' },
      { name: '426', type: 'bath_men' },
      { name: '427', type: 'class' },
      { name: '428', type: 'class' },
      { name: '429', type: 'class' },
      { name: '430', type: 'class' },
      { name: '502' },
      { name: '503', type: 'class' },
      {
        name: '504',
        type: 'lab_teach',
        alt_name_en: 'Interpretation Laboratory',
        alt_name_fr: 'Laboratoire d\'interprétation',
      },
      { name: '505' },
      { name: '506' },
      { name: '507' },
      { name: '510' },
      { name: '511' },
    ],
  },

  {
    shorthand: 'SMN',
    image: require('../images/buildings/full/SMN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/SMN.jpg'),
    name_en: 'Academic Hall',
    name_fr: 'Salle académique',
    location: {
      latitude: 45.425135,
      longitude: -75.686424,
    },
    address_en: '133/135 Séraphin Marion Private',
    address_fr: '133/135, rue Séraphin Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STE',
    image: require('../images/buildings/full/STE.jpg'),
    thumbnail: require('../images/buildings/thumbnail/STE.jpg'),
    name: 'SITE',
    location: {
      latitude: 45.419359,
      longitude: -75.678692,
    },
    address_en: '800 King Edward Avenue',
    address_fr: '800, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STN',
    image: require('../images/buildings/full/STN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/STN.jpg'),
    name_en: 'Stanton Residence',
    name_fr: 'Résidence Stanton',
    location: {
      latitude: 45.422398,
      longitude: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STT',
    image: require('../images/buildings/full/STT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/STT.jpg'),
    name: '1 Stewart',
    location: {
      latitude: 45.425652,
      longitude: -75.687365,
    },
    address_en: '1 Stewart Street',
    address_fr: '1, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SWT',
    image: require('../images/buildings/full/SWT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/SWT.jpg'),
    name_en: 'Centre for Academic Leadership',
    name_fr: 'Centre de leadership scolaire',
    location: {
      latitude: 45.425853,
      longitude: -75.686582,
    },
    address_en: '30/32 Stewart Street',
    address_fr: '30/32, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'TBT',
    image: require('../images/buildings/full/TBT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/TBT.jpg'),
    name_en: 'Tabaret Hall',
    name_fr: 'Pavillon Tabaret',
    location: {
      latitude: 45.424683,
      longitude: -75.685877,
    },
    address_en: '75 Laurier Avenue East',
    address_fr: '75, avenue Laurier est',
    facilities: [
      'food',
    ],
    rooms: [
      { name: 'W005' },
      { name: 'W007' },
      { name: 'W0011A' },
      { name: 'W0011C' },
      { name: 'W0011D' },
      { name: 'W0011F' },
      { name: 'W0011G' },
      { name: 'W0011H' },
      { name: 'W0011J' },
      { name: 'W0013', type: 'meeting' },
      { name: 'W0015' },
      { name: 'W0019', type: 'seminar' },
      { name: 'W0021', type: 'seminar' },
      {
        name: 'W0025',
        type: 'service',
        alt_name_en: 'Regional Mentoring Program',
        alt_name_fr: 'Programme de mentoray régional',
      },
      { name: 'W0029', type: 'test' },
      {
        name: 'W0031',
        type: 'service',
        alt_name_en: 'Regional Mentoring Program',
        alt_name_fr: 'Programme de mentoray régional',
      },
      { name: 'W0035' },
      { name: 'W0037' },
      { name: 'W0039' },
      { name: 'W0041' },
      { name: 'W0043' },
      { name: 'W0045' },

      { name: 'C03', type: 'store' },
      { name: 'C06' },
      { name: 'C07' },
      { name: 'C08' },
      { name: 'C010' },
      { name: 'C011' },
      {
        name: 'C012',
        type: 'service',
        alt_name_en: 'Human Resources - Centre for Organizational Development and Learning',
        alt_name_fr: 'Ressources humaines - Centre d\'apprentissage et de développement organisationnel',
      },
      { name: 'C013' },
      {
        name: 'C015',
        type: 'service',
        alt_name_en: 'Financial Planning',
        alt_name_fr: 'Service de planification financière',
      },
      { name: 'C016' },
      {
        name: 'C017',
        type: 'service',
        alt_name_en: 'Human Resources - Health, Wellness and Leave',
        alt_name_fr: 'Ressources humaines - Santé, mieux-être et congés',
      },
      { name: 'C018' },
      {
        name: 'C019',
        type: 'service',
        alt_name_en: 'Human Resources - Reception',
        alt_name_fr: 'Ressources humaines - Réception',
      },
      {
        name: 'W035',
        type: 'service',
        alt_name_en: 'Financial Services',
        alt_name_fr: 'Services des finances',
      },
      {
        name: 'L046',
        type: 'service',
        alt_name_en: 'Human Resources - Administration',
        alt_name_fr: 'Ressources humaines - Administration',
      },
      { name: 'L054' },
      { name: 'L055' },
      { name: 'L057' },
      { name: 'L058' },
      { name: 'L060' },
      { name: 'L062' },
      { name: 'L064' },
      { name: 'L066' },
      { name: 'L070', type: 'class' },
      { name: 'M082', type: 'meet' },
      {
        name: 'M083',
        type: 'service',
        alt_name_en: 'Senate Chamber',
        alt_name_fr: 'Salle du Sénat',
      },
      {
        name: 'M084',
        type: 'cafe',
        alt_name: 'Go Café',
      },
      { name: 'M086', type: 'study' },
      { name: 'M087' },
      { name: 'M090' },
      { name: 'M095' },
      { name: 'N0100' },
      { name: 'N0101' },
      { name: 'N0102' },
      { name: 'N0103' },
      { name: 'N0104' },
      { name: 'N0107' },
      { name: 'N0109' },
      { name: 'N0110' },
      { name: 'N0112' },
      { name: 'N0113' },
      { name: 'N0114' },
      { name: 'N0115' },
      { name: 'N0116' },
      { name: 'N0117' },
      { name: 'N0119' },
      { name: 'N0120' },
      { name: 'N0121' },
      { name: 'N0122' },
      { name: 'N0123' },
      { name: 'N0126' },

      { name: 'C101' },
      { name: 'N104' },
      { name: 'C105' },
      { name: 'N105' },
      { name: 'N106' },
      {
        name: 'C107',
        type: 'service',
        alt_name: 'InfoAdmission',
      },
      { name: 'N107' },
      { name: 'N108' },
      { name: 'C109' },
      {
        name: 'N109',
        alt_name_en: 'Office of Undergraduate Research',
        alt_name_fr: 'Bureau de la recherche au premier cycle',
      },
      { name: 'N110' },
      { name: 'C111' },
      { name: 'N111' },
      { name: 'N112' },
      {
        name: 'W112',
        type: 'auditorium',
        alt_name_en: 'Huguette-Labelle Hall',
        alt_name_fr: 'Salle Huguette-Labelle',
      },
      { name: 'N113' },
      { name: 'N114' },
      { name: 'C115', type: 'study' },
      { name: 'C116', type: 'study' },
      { name: 'C117', type: 'study' },
      { name: 'C118', type: 'study' },
      { name: 'C119', type: 'meet' },
      { name: 'C124' },
      { name: 'C125' },
      { name: 'C129' },
      { name: 'M151' },
      {
        name: 'M153',
        alt_name_en: 'Office of the Registrar, Strategic Enrollment Management',
        alt_name_fr: 'Cabinet du registraire, Gestion des effectifs solaires',
      },
      {
        name: 'M154',
        alt_name_en: 'Office of Research Ethics and Integrity',
        alt_name_fr: 'Bureau \'éthique et d\'intégrité de la recherche',
      },
      { name: 'M155' },
      { name: 'M156' },
      { name: 'M158', type: 'meet' },
      {
        name: 'M159',
        type: 'service',
        alt_name_en: 'Research Management Services',
        alt_name_fr: 'Service de gestion de la recherche',
      },
      {
        name: 'M160',
        alt_name_en: 'Grants and Ethics',
        alt_name_fr: 'Subventions et Déontologie',
      },
      { name: 'M162' },

      { name: 'C201' },
      { name: 'N201' },
      { name: 'N202' },
      { name: 'N203', type: 'meet' },
      { name: 'C205' },
      { name: 'N205', type: 'bath_women' },
      { name: 'N206' },
      { name: 'N207' },
      { name: 'N208' },
      { name: 'N209' },
      { name: 'N210', type: 'bath_men' },
      { name: 'C211' },
      { name: 'N211' },
      { name: 'C212' },
      { name: 'N212' },
      { name: 'C213' },
      { name: 'N213' },
      { name: 'C214' },
      { name: 'N214' },
      { name: 'N215', type: 'meet' },
      { name: 'C216' },
      { name: 'N216' },
      { name: 'C217' },
      { name: 'C218' },
      { name: 'C219' },
      { name: 'N219' },
      { name: 'N220' },
      { name: 'N221' },
      { name: 'N222' },
      { name: 'L224' },
      { name: 'L226' },
      { name: 'L228' },
      { name: 'L230' },
      { name: 'L234' },
      { name: 'L236' },
      { name: 'L238' },
      { name: 'L239' },
      { name: 'L242' },
      { name: 'L244' },
      { name: 'L246' },
      { name: 'L250' },
      { name: 'M280', type: 'meet' },
      { name: 'M281' },
      { name: 'M282', type: 'bath_uni' },
      { name: 'M283' },
      { name: 'M285' },
      { name: 'M286' },
      { name: 'M287' },

      { name: 'C301' },
      {
        name: 'C302',
        type: 'service',
        alt_name_en: 'Legal Services',
        alt_name_fr: 'Services juridiques',
      },
      {
        name: 'C304',
        alt_name_en: 'Michaëlle Jean Centre for Global and Community Engagement',
        alt_name_fr: 'Centre Michaëlle-Jean pour l\'engagement mondial et communautaire',
      },
      { name: 'C305' },
      { name: 'C306' },
      { name: 'C307' },
      { name: 'C309', type: 'class' },
      { name: 'C311', type: 'class' },
      { name: 'C315', type: 'class' },
      { name: 'L316' },
      { name: 'C317', type: 'class' },
      { name: 'L318' },
      { name: 'C319', type: 'class' },
      { name: 'L320' },
      { name: 'W321' },
      { name: 'L322' },
      { name: 'W323', type: 'class' },
      { name: 'W325', type: 'class' },
      { name: 'L326' },
      { name: 'W327', type: 'class' },
      { name: 'L328' },
      { name: 'L330' },
      { name: 'L332' },
      { name: 'W333', type: 'class' },
      { name: 'L334' },
      { name: 'L336' },
      { name: 'L338' },
      { name: 'L340', type: 'meet' },
      { name: 'C364' },
      { name: 'C367' },
      { name: 'C370' },
      { name: 'C370D' },
      {
        name: 'L378',
        alt_name_en: 'Faculty of Science',
        alt_name_fr: 'Faculté des sciences',
      },
      { name: 'M381' },
      { name: 'M382' },
      { name: 'M383' },
      {
        name: 'M386',
        alt_name_en: 'International Office',
        alt_name_fr: 'Bureau international',
      },
      { name: 'M388' },
      { name: 'M389' },
      { name: 'M390' },
      { name: 'M391' },

      { name: 'M400' },
      { name: 'M402' },
      { name: 'M403' },
      { name: 'M404' },
      { name: 'M405' },
      { name: 'M406' },
      { name: 'M407' },
      { name: 'M408' },
      { name: 'M409' },
      { name: 'M410' },
      { name: 'M411' },
      { name: 'M413' },
      { name: 'M415' },
      { name: 'C452' },
      { name: 'C457' },
    ],
  },

  {
    shorthand: 'THN',
    image: require('../images/buildings/full/THN.jpg'),
    thumbnail: require('../images/buildings/thumbnail/THN.jpg'),
    name_en: 'Thompson Residence',
    name_fr: 'Résidence Thompson',
    location: {
      latitude: 45.424130,
      longitude: -75.683206,
    },
    address_en: '25 University Private',
    address_fr: '25, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'UCU',
    image: require('../images/buildings/full/UCU.jpg'),
    thumbnail: require('../images/buildings/thumbnail/UCU.jpg'),
    name_en: 'Jock-Turcot University Centre',
    name_fr: 'Centre universitaire Jock-Turcot',
    location: {
      latitude: 45.422557,
      longitude: -75.683307,
    },
    address_en: '85 University Private',
    address_fr: '85, privé University',
    facilities: [
      'atm',
      'food',
      'printer',
      'store',
      'alcohol',
    ],
    rooms: [
      { name: 'AUD', type: 'class' },
      {
        name: '0015',
        type: 'service',
        alt_name_en: 'Food Bank',
        alt_name_fr: 'Banque alimentaire',
      },
      {
        name: '0021',
        type: 'service',
        alt_name_en: 'SFUO - Accounting',
        alt_name_fr: 'FÉUO - Comptabilité',
      },
      {
        name: '0022',
        type: 'service',
        alt_name_en: 'SFUO - Promotions and Marketing',
        alt_name_fr: 'FÉUO - Promotions et marketing',
      },
      {
        name: '0024',
        type: 'service',
        alt_name: 'docUcentre',
      },
      {
        name: '0025F',
        alt_name_en: 'Translations Department',
        alt_name_fr: 'Département des traductions',
      },
      {
        name: '0030',
        alt_name_en: 'Zoom Productions',
        alt_name_fr: 'Productions Zoom',
      },
      {
        name: '02A',
        type: 'service',
        alt_name_en: 'Crime Prevention - Lost and Found Service',
        alt_name_fr: 'Prévention du crime - Service des objets perdus et retrouvés',
      },
      {
        name: '03',
        type: 'store',
        alt_name_en: 'Campus Store',
        alt_name_fr: 'Boutique Campus',
      },
      {
        name: '04',
        type: 'service',
        alt_name_en: 'Teach Abroad Information Centre',
        alt_name_fr: 'entre d\'information pour enseigner à l\'étranger',
      },
      {
        name: '07',
        type: 'service',
        alt_name_en: 'SFUO',
        alt_name_fr: 'FÉUO',
      },
      {
        name: '08A',
        type: 'service',
        alt_name_en: 'Foot Patrol',
        alt_name_fr: 'Service de raccompagnement',
      },
      {
        name: '026',
        type: 'service',
        alt_name: 'Carrefour francophone',
      },
      {
        name: '028',
        type: 'service',
        alt_name: 'Portraits Now',
      },
      {
        name: '030',
        type: 'service',
        alt_name_en: 'Student Clubs',
        alt_name_fr: 'Clubs étudiants',
      },
      {
        name: '031B',
        type: 'service',
        alt_name_en: 'Bilingualism Centre',
        alt_name_fr: 'Centre de bilinguisme',
      },
      {
        name: '034',
        type: 'store',
        alt_name: 'Pivik',
      },
      {
        name: '101',
        type: 'service',
        alt_name_en: 'Student Rights Centre',
        alt_name_fr: 'Centre des droits étudiants',
      },
      { name: '102', type: 'study' },
      {
        name: '104',
        type: 'service',
        alt_name_en: 'uOttawa Card Service',
        alt_name_fr: 'Service de la cater uOttawa',
      },
      {
        name: '106',
        alt_name_en: 'Association of Part Time Professors University of Ottawa',
        alt_name_fr: 'Association des professeur.e.s à temps partie Université d\'Ottawa',
      },
      {
        name: '107',
        type: 'service',
        alt_name_en: 'Multi-Faith Room',
        alt_name_fr: 'Salle Multi-Foi',
      },
      {
        name: '120',
        type: 'cafe',
        alt_name_en: '24/7 Dining Hall',
        alt_name_fr: 'Salle à manger 24/7',
      },
      {
        name: '203',
        type: 'service',
        alt_name_en: 'Health Promotion',
        alt_name_fr: 'Promotion de la santé',
      },
      {
        name: '204',
        type: 'service',
        alt_name_en: 'Health Promotion Department',
        alt_name_fr: 'Département Promotion de la santé',
      },
      { name: '205', type: 'class' },
      { name: '206', type: 'meet' },
      { name: '207', type: 'meet' },
      { name: '211B', type: 'service' },
      {
        name: '211D',
        type: 'service',
        alt_name_en: 'Peer Help Centre',
        alt_name_fr: 'Centre d\'entraide',
      },
      {
        name: '211E',
        type: 'service',
        alt_name_en: 'International House',
        alt_name_fr: 'Maison Internationale',
      },
      {
        name: '211F',
        type: 'service',
        alt_name_en: 'Centre for students with disabilities',
        alt_name_fr: 'Centre des étudiants ayant un handicap',
      },
      { name: '211G', type: 'service' },
      { name: '211J', type: 'service' },
      { name: '215A', type: 'service' },
      { name: '215B', type: 'service' },
      { name: '215C', type: 'service' },
      {
        name: '215D',
        type: 'service',
        alt_name_en: 'Ontario Public Interest Research Group',
        alt_name_fr: 'Group de recherche d\'intérêt de l\'Ontario',
      },
      { name: '215E', type: 'service' },
      {
        name: '215F',
        type: 'service',
        alt_name_en: 'SFUO - Sustainable Development',
        alt_name_fr: 'FÉUO - Développement durable',
      },
      { name: '215G', type: 'service' },
      {
        name: '216',
        type: 'cafe',
        alt_name: '1848',
      },
      { name: '218' },
      {
        name: '219',
        type: 'food',
        alt_name: 'Tim Horton\'s',
      },
      {
        name: '220',
        type: 'service',
        alt_name_en: 'SFUO - Women\'s Resource Centre',
        alt_name_fr: 'Centre de ressources des femmes',
      },
      { name: '230', type: 'study' },
      { name: '232', type: 'study' },
      { name: '301A', type: 'meet' },
      { name: '301B', type: 'study' },
      { name: '301C', type: 'study' },
      {
        name: '303',
        alt_name_en: 'CUPE Local 2626',
        alt_name_fr: 'SCFP 2626',
      },
      {
        name: '307',
        alt_name_en: 'Ombudsperson\'s Office',
        alt_name_fr: 'Bureau de l\'Ombudsman',
      },
      { name: '309' },
      { name: '311' },
      {
        name: '312',
        type: 'service',
        alt_name_en: 'Career Development Centre',
        alt_name_fr: 'Centre de développement de carrière',
      },
      {
        name: '318',
        type: 'service',
        alt_name_en: 'Community Life',
        alt_name_fr: 'Vie communautaire',
      },
      { name: '319' },
      { name: '320' },
      { name: '320A' },
      { name: '322' },
      { name: '323' },
      {
        name: '323B',
        type: 'service',
        alt_name_en: 'Nursing Room',
        alt_name_fr: 'Salle d\'allaitement',
      },
      {
        name: '324',
        type: 'service',
        alt_name_en: 'Multi-Faith Chaplaincy Services',
        alt_name_fr: 'Services d\'aumônerie multiconfessionnelle',
      },
      { name: '325' },
      { name: '328' },
      { name: '330' },
      { name: '332' },
      {
        name: '333',
        alt_name_en: 'Service Excellence',
        alt_name_fr: 'L\'Excellence du service',
      },
      { name: '336' },
      {
        name: '339',
        alt_name_en: 'Conventions and Reservations',
        alt_name_fr: 'Congrés et réservations',
      },
      { name: '340' },
      { name: '341' },
      {
        name: '344',
        type: 'service',
        alt_name_en: 'Food Services',
        alt_name_fr: 'Service alimentaires',
      },
      { name: '345' },
      { name: '346' },
    ],
  },

  {
    shorthand: 'UOHS FHT/ÉSF du SSUO',
    image: require('../images/buildings/full/UOHSFHT.jpg'),
    thumbnail: require('../images/buildings/thumbnail/UOHSFHT.jpg'),
    name_en: 'UOHS - Family Health Team',
    name_fr: 'SSUO - L\'Équipe de santé familiale',
    location: {
      latitude: 45.428973,
      longitude: -75.684934,
    },
    address_en: '316 Rideau Street',
    address_fr: '316, rue Rideau',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'UOITP/PTIUO',
    image: require('../images/buildings/full/UOITP.jpg'),
    thumbnail: require('../images/buildings/thumbnail/UOITP.jpg'),
    name_en: 'UOITP - University of Ottawa IT Professionals',
    name_fr: 'PTIUO - Professionels des technologies de l\'information de l\'Université d\'Ottawa',
    location: {
      latitude: 45.425848,
      longitude: -75.686444,
    },
    address_en: '34/36 Stewart Street',
    address_fr: '34/36, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'VNR',
    image: require('../images/buildings/full/VNR.jpg'),
    thumbnail: require('../images/buildings/thumbnail/VNR.jpg'),
    name_en: 'Vanier Hall',
    name_fr: 'Pavillon Vanier',
    location: {
      latitude: 45.421487,
      longitude: -75.683413,
    },
    address_en: '136 Jean-Jacques Lussier Private',
    address_fr: '136, rue Jean-Jacques Lussier',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'WCA',
    image: require('../images/buildings/full/WCA.jpg'),
    thumbnail: require('../images/buildings/thumbnail/WCA.jpg'),
    name_en: 'William Commanda Hall',
    name_fr: 'Pavillon William Commanda',
    location: {
      latitude: 45.423165,
      longitude: -75.684842,
    },
    address_en: '52 University Private',
    address_fr: '52, privé University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'WLD',
    image: require('../images/buildings/full/WLD.jpg'),
    thumbnail: require('../images/buildings/thumbnail/WLD.jpg'),
    name: '200 Wilbrod',
    location: {
      latitude: 45.426043,
      longitude: -75.684203,
    },
    address_en: '200 Wilbrod Street',
    address_fr: '200, rue Wilbrod',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '17 Copernicus',
    image: require('../images/buildings/full/17Copernicus.jpg'),
    thumbnail: require('../images/buildings/thumbnail/17Copernicus.jpg'),
    name_en: 'Community Legal Clinic',
    name_fr: 'Clinique juridique communautaire',
    location: {
      latitude: 45.423824,
      longitude: -75.684096,
    },
    address_en: '17 Copernicus Street',
    address_fr: '17, rue Copernicus',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '34 Copernicus',
    image: require('../images/buildings/full/34Copernicus.jpg'),
    thumbnail: require('../images/buildings/thumbnail/34Copernicus.jpg'),
    name_en: 'Centre for Bahá\'i Studies',
    name_fr: 'Centre d\'études bahá\'ies',
    location: {
      latitude: 45.424885,
      longitude: -75.683797,
    },
    address_en: '34 Copernicus Street',
    address_fr: '34, rue Copernicus',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '38 Stewart',
    image: require('../images/buildings/full/38Stewart.jpg'),
    thumbnail: require('../images/buildings/thumbnail/38Stewart.jpg'),
    name_en: 'External Relations',
    name_fr: 'Relations extérieures',
    location: {
      latitude: 45.425926,
      longitude: -75.686433,
    },
    address_en: '38 Stewart Street',
    address_fr: '38, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '40 Stewart',
    image: require('../images/buildings/full/40Stewart.jpg'),
    thumbnail: require('../images/buildings/thumbnail/40Stewart.jpg'),
    name_en: 'Bilingual Canadian Dictionary',
    name_fr: 'Dictionnaire Canadien bilingue',
    location: {
      latitude: 45.425945,
      longitude: -75.686390,
    },
    address_en: '40 Stewart Street',
    address_fr: '40, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '113 Osgoode',
    image: require('../images/buildings/full/113Osgoode.jpg'),
    thumbnail: require('../images/buildings/thumbnail/113Osgoode.jpg'),
    name_en: 'Association des juristes d\'expression française de l\'Ontario and Legal Translation and Documentation Centre',
    name_fr: 'Association des juristes d\'expression française de l\'Ontario et Centre de traduction et de documentation juridiques',
    location: {
      latitude: 45.424066,
      longitude: -75.6830636,
    },
    address_en: '113 Osgoode Street',
    address_fr: '113, rue Osgoode',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '143 Séraphin-Marion',
    image: require('../images/buildings/full/143Seraphin.jpg'),
    thumbnail: require('../images/buildings/thumbnail/143Seraphin.jpg'),
    name: '143 Séraphin-Marion',
    location: {
      latitude: 45.425664,
      longitude: -75.685695,
    },
    address_en: '143 Séraphin-Marion Private',
    address_fr: '143, rue Séraphin-Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '170 Waller',
    image: require('../images/buildings/full/170Waller.jpg'),
    thumbnail: require('../images/buildings/thumbnail/170Waller.jpg'),
    name: 'APUO',
    location: {
      latitude: 45.422888,
      longitude: -75.686271,
    },
    address_en: '170 Waller Street',
    address_fr: '170, rue Waller',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '190 Laurier',
    image: require('../images/buildings/full/190Laurier.jpg'),
    thumbnail: require('../images/buildings/thumbnail/190Laurier.jpg'),
    name_en: 'Development Office',
    name_fr: 'Bureau du développement',
    location: {
      latitude: 45.425265,
      longitude: -75.682407,
    },
    address_en: '190 Laurier Avenue East',
    address_fr: '190, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '538 King Edward',
    image: require('../images/buildings/full/538KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/538KingEdward.jpg'),
    name_en: 'Faculty of Health Sciences Dean\'s Office and Administration',
    name_fr: 'Faculté de sciences de la santé Décanat et administration',
    location: {
      latitude: 45.424984,
      longitude: -75.682841,
    },
    address_en: '538 King Edward Avenue',
    address_fr: '538, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '542 King Edward',
    image: require('../images/buildings/full/542KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/542KingEdward.jpg'),
    name_en: 'University of Ottawa Press',
    name_fr: 'Les Presses de l\'Université d\'Ottawa',
    location: {
      latitude: 45.424860,
      longitude: -75.682800,
    },
    address_en: '542 King Edward Avenue',
    address_fr: '542, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '545 King Edward',
    image: require('../images/buildings/full/545KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/545KingEdward.jpg'),
    name_en: 'Resources and Information Office',
    name_fr: 'Bureau des ressources et de l\'information',
    location: {
      latitude: 45.424991,
      longitude: -75.682568,
    },
    address_en: '545 King Edward Avenue',
    address_fr: '545, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '554 King Edward',
    image: require('../images/buildings/full/554KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/554KingEdward.jpg'),
    name_en: 'Faculty of Law',
    name_fr: 'Faculté de droit',
    location: {
      latitude: 45.424519,
      longitude: -75.682514,
    },
    address_en: '554 King Edward Avenue',
    address_fr: '554, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '556 King Edward',
    image: require('../images/buildings/full/556KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/556KingEdward.jpg'),
    name_en: 'Department of Communication',
    name_fr: 'Département de communication',
    location: {
      latitude: 45.424326,
      longitude: -75.682073,
    },
    address_en: '556 King Edward Avenue',
    address_fr: '556, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '558 King Edward',
    image: require('../images/buildings/full/558KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/558KingEdward.jpg'),
    name_en: 'Department of Communication',
    name_fr: 'Département de communication',
    location: {
      latitude: 45.424326,
      longitude: -75.682073,
    },
    address_en: '558 King Edward Avenue',
    address_fr: '558, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '559 King Edward',
    image: require('../images/buildings/full/559KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/559KingEdward.jpg'),
    name_en: 'Chair of Ukrainian Studies, Support Staff - OSSTF, and Regroupement des organismes du patrimoine franco-ontarien',
    name_fr: 'Chair détudes ukrainiennes, Personnel de soutien - FEÉSO, et Regroupement des organismes du patrimoine franco-ontarien',
    location: {
      latitude: 45.424860,
      longitude: -75.682270,
    },
    address_en: '559 King Edward Avenue',
    address_fr: '559, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '562 King Edward',
    image: require('../images/buildings/full/562KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/562KingEdward.jpg'),
    name_en: 'Official Languages and Bilingualism Institute',
    name_fr: 'Institut des langues officielles et du bilinguisme',
    location: {
      latitude: 45.424243,
      longitude: -75.682273,
    },
    address_en: '562 King Edward Avenue',
    address_fr: '562, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '577 King Edward',
    image: require('../images/buildings/full/577KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/577KingEdward.jpg'),
    name_en: 'Canadian Mathematical Society',
    name_fr: 'Société mathématique du Canada',
    location: {
      latitude: 45.424644,
      longitude: -75.682113,
    },
    address_en: '577 King Edward Avenue',
    address_fr: '577, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '598 King Edward',
    image: require('../images/buildings/full/598KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/598KingEdward.jpg'),
    name_en: 'Department of Physics',
    name_fr: 'Département de physique',
    location: {
      latitude: 45.424011,
      longitude: -75.681805,
    },
    address_en: '598 King Edward Avenue',
    address_fr: '598, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '600 King Edward',
    image: require('../images/buildings/full/600KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/600KingEdward.jpg'),
    name_en: 'Bernard Syron Law Student Centre',
    name_fr: 'Centre des étudiants en droit Bernard Syron',
    location: {
      latitude: 45.423937,
      longitude: -75.681923,
    },
    address_en: '600 King Edward Avenue',
    address_fr: '600, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '600 Peter Morand',
    image: require('../images/buildings/full/600PeterMorand.jpg'),
    thumbnail: require('../images/buildings/thumbnail/600PeterMorand.jpg'),
    name_en: 'Interprofessional Rehabilitation Clinic',
    name_fr: 'Clinique interprofessionnelle de réadaptation',
    location: {
      latitude: 45.403144,
      longitude: -75.642256,
    },
    address_en: '600 Peter Morand Crescent',
    address_fr: '600, rue Peter Morand',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '603 King Edward',
    image: require('../images/buildings/full/603KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/603KingEdward.jpg'),
    name_en: 'Canada Research Chair on Occupational Health and Safety Law',
    name_fr: 'Chaire de recherche du Canada en droit de la santé et de la sécurité du travail',
    location: {
      latitude: 45.423946,
      longitude: -75.681706,
    },
    address_en: '603 King Edward Avenue',
    address_fr: '603, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '647 King Edward',
    image: require('../images/buildings/full/647KingEdward.jpg'),
    thumbnail: require('../images/buildings/thumbnail/647KingEdward.jpg'),
    name_en: 'Free Store',
    name_fr: 'Gratuiterie',
    location: {
      latitude: 45.422870,
      longitude: -75.680793,
    },
    address_en: '647 King Edward Avenue',
    address_fr: '647, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '850 Peter Morand',
    image: require('../images/buildings/full/850PeterMorand.jpg'),
    thumbnail: require('../images/buildings/thumbnail/850PeterMorand.jpg'),
    name: '850 Peter Morand',
    location: {
      latitude: 45.402696,
      longitude: -75.642303,
    },
    address_en: '850 Peter Morand Crescent',
    address_fr: '850, rue Peter Morand',
    facilities: [],
    rooms: [],
  },

];
