/**
 *
 * @license
 * Copyright (C) 2016 Joseph Roque
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @author Joseph Roque
 * @file Buildings.js
 * @description Provides names and images of all buildings on the University of Ottawa campus.
 *
 */
'use strict';

/* eslint-disable */

module.exports = [

  {
    shorthand: '3',
    image: require('../images/buildings/3.jpg'),
    name_en: 'William Commanda Hall',
    name_fr: 'Pavillon William Commanda',
    location: {
      lat: 45.423165,
      long: -75.684842,
    },
    address_en: '52 University Private',
    address_fr: '52, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '34',
    image: require('../images/buildings/34.jpg'),
    name_en: 'Centre for Bahá\'i Studies',
    name_fr: 'Centre d\'études bahá\'ies',
    location: {
      lat: 45.424885,
      long: -75.683797,
    },
    address_en: '34 Copernicus Street',
    address_fr: '34, rue Copernicus',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '109',
    image: require('../images/buildings/109.jpg'),
    name: 'La Rotonde',
    location: {
      lat: 45.424038,
      long: -75.680850,
    },
    address_en: '109 Osgoode Street',
    address_fr: '109, rue Osgoode',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '113',
    image: require('../images/buildings/113.jpg'),
    name_en: 'Association des juristes d\'expression française de l\'Ontario and Legal Translation and Documentation Centre',
    name_fr: 'Association des juristes d\'expression française de l\'Ontario et Centre de traduction et de documentation juridiques',
    location: {
      lat: 45.424066,
      long: -75.6830636,
    },
    address_en: '113 Osgoode Street',
    address_fr: '113, rue Osgoode',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '242',
    image: require('../images/buildings/242.jpg'),
    name_en: 'UOITP - University of Ottawa IT Professionals',
    name_fr: 'PTIUO - Professionels des technologies de l\'information de l\'Université d\'Ottawa',
    location: {
      lat: 45.425848,
      long: -75.686444,
    },
    address_en: '34/36 Stewart Street',
    address_fr: '34/36, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '243',
    image: require('../images/buildings/243.jpg'),
    name_en: 'External Relations',
    name_fr: 'Relations extérieures',
    location: {
      lat: 45.425926,
      long: -75.686433,
    },
    address_en: '38 Stewart Street',
    address_fr: '38, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '244',
    image: require('../images/buildings/244.jpg'),
    name_en: 'Bilingual Canadian Dictionary',
    name_fr: 'Dictionnaire Canadien bilingue',
    location: {
      lat: 45.425945,
      long: -75.686390,
    },
    address_en: '40 Stewart Street',
    address_fr: '40, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '275',
    image: require('../images/buildings/275.jpg'),
    name_en: 'Community Legal Clinic',
    name_fr: 'Clinique juridique communautaire',
    location: {
      lat: 45.423824,
      long: -75.684096,
    },
    address_en: '17 Copernicus Street',
    address_fr: '17, rue Copernicus',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '538',
    image: require('../images/buildings/538.jpg'),
    name_en: 'Faculty of Health Sciences Dean\'s Office and Administration',
    name_fr: 'Faculté de sciences de la santé Décanat et administration',
    location: {
      lat: 45.424984,
      long: -75.682841,
    },
    address_en: '538 King Edward Avenue',
    address_fr: '538, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '542',
    image: require('../images/buildings/542.jpg'),
    name_en: 'University of Ottawa Press',
    name_fr: 'Les Presses de l\'Université d\'Ottawa',
    location: {
      lat: 45.424860,
      long: -75.682800,
    },
    address_en: '542 King Edward Avenue',
    address_fr: '542, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '545',
    image: require('../images/buildings/545.jpg'),
    name_en: 'Reosurces and Information Office',
    name_fr: 'Bureau des ressources et de l\'information',
    location: {
      lat: 45.424991,
      long: -75.682568,
    },
    address_en: '545 King Edward Avenue',
    address_fr: '545, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '554',
    image: require('../images/buildings/554.jpg'),
    name_en: 'Faculty of Law',
    name_fr: 'Faculté de droit',
    location: {
      lat: 45.424519,
      long: -75.682514,
    },
    address_en: '554 King Edward Avenue',
    address_fr: '554, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '556',
    image: require('../images/buildings/556.jpg'),
    name_en: 'Department of Communication',
    name_fr: 'Département de communication',
    location: {
      lat: 45.424326,
      long: -75.682073,
    },
    address_en: '556 King Edward Avenue',
    address_fr: '556, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '558',
    image: require('../images/buildings/558.jpg'),
    name_en: 'Department of Communication',
    name_fr: 'Département de communication',
    location: {
      lat: 45.424326,
      long: -75.682073,
    },
    address_en: '558 King Edward Avenue',
    address_fr: '558, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '559',
    image: require('../images/buildings/559.jpg'),
    name_en: 'Chair of Ukranian Studies, Support Staff - OSSTF, and Regroupement des organismes du patrimoine franco-ontarien',
    name_fr: 'Chair détudes ukrainiennes, Personnel de soutien - FEÉSO, et Regroupement des organismes du patrimoine franco-ontarien',
    location: {
      lat: 45.424860,
      long: -75.682270,
    },
    address_en: '559 King Edward Avenue',
    address_fr: '559, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '562',
    image: require('../images/buildings/562.jpg'),
    name_en: 'Official Languages and Bilingualism Institute',
    name_fr: 'Institut des langues officielles et du bilinguisme',
    location: {
      lat: 45.424243,
      long: -75.682273,
    },
    address_en: '562 King Edward Avenue',
    address_fr: '562, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '577',
    image: require('../images/buildings/577.jpg'),
    name_en: 'Canadian Mathematical Society',
    name_fr: 'Société mathématique du Canada',
    location: {
      lat: 45.424644,
      long: -75.682113,
    },
    address_en: '577 King Edward Avenue',
    address_fr: '577, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '598',
    image: require('../images/buildings/598.jpg'),
    name_en: 'Department of Physics',
    name_fr: 'Département de physique',
    location: {
      lat: 45.424011,
      long: -75.681805,
    },
    address_en: '598 King Edward Avenue',
    address_fr: '598, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '600',
    image: require('../images/buildings/600.jpg'),
    name_en: 'Bernard Syron Law Student Centre',
    name_fr: 'Centre des étudiants en droit Bernard Syron',
    location: {
      lat: 45.423937,
      long: -75.681923,
    },
    address_en: '600 King Edward Avenu',
    address_fr: '600, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '603',
    image: require('../images/buildings/603.jpg'),
    name_en: 'Canada Research Chair on Occupational Health and Safety Law',
    name_fr: 'Chaire de recherche du Canada en droit de la santé et de la sécurité du travail',
    location: {
      lat: 45.423946,
      long: -75.681706,
    },
    address_en: '603 King Edward Avenue',
    address_fr: '603, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '647',
    image: require('../images/buildings/647.jpg'),
    name_en: 'Free Store',
    name_fr: 'Gratuiterie',
    location: {
      lat: 45.422870,
      long: -75.680793,
    },
    address_en: '647 King Edward Avenue',
    address_fr: '647, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: '90U',
    image: require('../images/buildings/90U.jpg'),
    name_en: '90 University',
    name_fr: '90 Université',
    location: {
      lat: 45.422398,
      long: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'ARC',
    image: require('../images/buildings/ARC.jpg'),
    name_en: 'Advanced Research Centre',
    name_fr: 'Complexe de recherche avancée',
    location: {
      lat: 45.420723,
      long: -75.678712,
    },
    address_en: '25 Templeton Street',
    address_fr: '25, rue Templeton',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'ATK',
    image: require('../images/buildings/ATK.jpg'),
    name_en: 'Alex Trebek Alumni Hall',
    name_fr: 'Pavillon des diplômés Alex-Trebek',
    location: {
      lat: 45.425135,
      long: -75.686424,
    },
    address_en: '155 Séraphin-Marion Private',
    address_fr: '155, rue Séraphin-Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'AWHC',
    image: require('../images/buildings/AWHC.jpg'),
    name_en: 'Academic Writing Help Centre',
    name_fr: 'Centre d’aide à la rédaction des travaux universitaires',
    location: {
      lat: 45.421908,
      long: -75.684414,
    },
    address_en: '110 University Private',
    address_fr: '110, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'BSC',
    image: require('../images/buildings/BSC.jpg'),
    name_en: 'Biosciences Complex',
    name_fr: 'Complexe des biosciences',
    location: {
      lat: 45.421329,
      long: -75.681500,
    },
    address_en: '30 Marie-Curie Private',
    address_fr: '30, rue Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'CRG',
    image: require('../images/buildings/CRG.jpg'),
    name: 'CAREG',
    location: {
      lat: 45.421134,
      long: -75.682059,
    },
    address_en: '20 Marie-Curie Private',
    address_fr: '20, rue Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'CTE',
    image: require('../images/buildings/CTE.jpg'),
    name_en: 'Power Plant',
    name_fr: 'Centrale thermique',
    location: {
      lat: 45.421031,
      long: -75.679920,
    },
    address_en: '720 King Edward Avenue',
    address_fr: '720, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'DMS',
    image: require('../images/buildings/DMS.jpg'),
    name_en: 'Desmarais Hall',
    name_fr: 'Pavillon Desmarais',
    location: {
      lat: 45.423884,
      long: -75.687202,
    },
    address_en: '55 Laurier Avenue East',
    address_fr: '55, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'DRO',
    image: require('../images/buildings/DRO.jpg'),
    name_en: 'D\'Iorio Hall',
    name_fr: 'Pavillon D\'Iorio',
    location: {
      lat: 45.420956,
      long: -75.681306,
    },
    address_en: '10 Marie-Curie Private',
    address_fr: '10, rue Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'FSS',
    image: require('../images/buildings/FSS.jpg'),
    name_en: 'Social Sciences Building',
    name_fr: 'Pavillon des Sciences sociales',
    location: {
      lat: 45.421541,
      long: -75.683783,
    },
    address_en: '120 University Private',
    address_fr: '120, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'FTX',
    image: require('../images/buildings/FTX.jpg'),
    name_en: 'Fauteux Hall',
    name_fr: 'Pavillon Fauteux',
    location: {
      lat: 45.423748,
      long: -75.682569,
    },
    address_en: '57 Louis-Pasteur Private',
    address_fr: '57, rue Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'GNN',
    image: require('../images/buildings/GNN.jpg'),
    name_en: 'Gendron Hall',
    name_fr: 'Pavillon Gendron',
    location: {
      lat: 45.421329,
      long: -75.681500,
    },
    address_en: '30 Marie-Curie Private',
    address_fr: '30, rue Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'GSD',
    image: require('../images/buildings/GSD.jpg'),
    name_en: 'GSAED Grad House',
    name_fr: 'Maison des Étudians Diplômés GSAED',
    location: {
      lat: 45.423824,
      long: -75.684096,
    },
    address_en: '601 Cumberland Street',
    address_fr: '601, rue Cumberland',
    facilities: [],
    rooms: [],
  },
  {
    shorthand: 'Henderson',
    image: require('../images/placeholders/outer_placeholder.jpg'),
    name_en: 'Henderson Residence',
    name_fr: 'Résidence Henderson',
    location: {
      lat: 45.4213294,
      long: -75.6805316,
    },
    address_en: '202 Henderson Avenue',
    address_fr: '202, avenue Henderson',
    facilities: [],
    rooms: [],
  },
  {
    shorthand: 'HGN',
    image: require('../images/buildings/HGN.jpg'),
    name_en: 'Hagen Hall',
    name_fr: 'Pavillon Hagen',
    location: {
      lat: 45.425482,
      long: -75.685541,
    },
    address_en: '115 Séraphin Marion Private',
    address_fr: '115, rue Séraphin Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'HSY',
    image: require('../images/buildings/HSY.jpg'),
    name_en: 'Hyman Soloway Residence',
    name_fr: 'Résidence Hyman Soloway',
    location: {
      lat: 45.425136,
      long: -75.684281,
    },
    address_en: '157 Laurier Avenue East',
    address_fr: '157, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'KEB',
    image: require('../images/buildings/KEB.jpg'),
    name_en: 'Fulcrum, OPIRG',
    name_fr: 'Fulcrum, GRIPO',
    location: {
      lat: 45.423211,
      long: -75.680906,
    },
    address_en: '631 King Edward Avenue',
    address_fr: '631, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'KED',
    image: require('../images/buildings/KED.jpg'),
    name_en: 'Department of Mathematics and Statistics',
    name_fr: 'Département de mathématiques et statistique',
    location: {
      lat: 45.424441,
      long: -75.681918,
    },
    address_en: '585 King Edward Avenue',
    address_fr: '585, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LBC',
    image: require('../images/buildings/LBC.jpg'),
    name_en: 'Leblanc Residence',
    name_fr: 'Résidence Leblanc',
    location: {
      lat: 45.423335,
      long: -75.682451,
    },
    address_en: '45 Louis-Pasteur Private',
    address_fr: '45, rue Louis-Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LMX',
    image: require('../images/buildings/LMX.jpg'),
    name_en: 'Lamoureux Hall',
    name_fr: 'Pavillon Lamoureux',
    location: {
      lat: 45.421521,
      long: -75.682128,
    },
    address_en: '145 Jean-Jacques Lussier Private',
    address_fr: '145, rue Jean-Jacques Lussier',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LPR',
    image: require('../images/buildings/LPR.jpg'),
    name_en: 'Louis-Pasteur',
    name_fr: 'Louis-Pasteur',
    location: {
      lat: 45.421136,
      long: -75.680287,
    },
    address_en: '141 Louis Pasteur Private',
    address_fr: '141, rue Louis Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LR3',
    image: require('../images/buildings/LR3.jpg'),
    name_en: 'Development Office',
    name_fr: 'Bureau du développement',
    location: {
      lat: 45.425265,
      long: -75.682407,
    },
    address_en: '190 Laurier Avenue East',
    address_fr: '190, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'LRR',
    image: require('../images/buildings/LRR.jpg'),
    name_en: '100 Laurier',
    name_fr: '100 Laurier',
    location: {
      lat: 45.424247,
      long: -75.685087,
    },
    address_en: '100 Laurier Avenue East',
    address_fr: '100, avenue Laurier est',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MCE',
    image: require('../images/buildings/MCE.jpg'),
    name: '100 Marie-Curie',
    location: {
      lat: 45.421752,
      long: -75.680984,
    },
    address_en: '100 Marie-Curie Private',
    address_fr: '100, rue Marie-Curie',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MHN',
    image: require('../images/buildings/MHN.jpg'),
    name_en: 'Hamelin Hall',
    name_fr: 'Pavillon Hamelin',
    location: {
      lat: 45.423807,
      long: -75.685800,
    },
    address_en: '70 Laurier Avenue East',
    address_fr: '70, avenue Laurier est',
    facilities: [
      'food',
      'printer',
      'library',
      'parking',
    ],
    rooms: [
      {
        name: '02',
        type: 'library',
        alt_name_en: 'Julien Couture Resource Centre',
        alt_name_fr: 'Centre de ressources Julien-Couture',
      },
      { name: '03' },
      { name: '04' },
      { name: '05' },
      { name: '06' },
      { name: '07' },
      { name: '08' },
      { name: '09' },
      { name: '010' },
      { name: '012' },
      { name: '013' },
      { name: '015' },
      { name: '016' },
      { name: '017' },
      { name: '018' },
      { name: '019' },
      {
        name: '020',
        type: 'lab_res',
        alt_name_en: 'J.A. Bombardier Foundation Room',
        alt_name_fr: 'Salle Fondation J.A. Bombardier',
      },
      { name: '021' },
      { name: '022' },
      { name: '023' },
      { name: '024' },
      { name: '025' },
      { name: '026' },
      { name: '027' },
      { name: '028' },
      { name: '029' },
      {
        name: '030',
        type: 'cafe',
        alt_name: 'GO Café',
      },
      { name: '033', type: 'class', },
      { name: '100' },
      { name: '101' },
      { name: '102' },
      { name: '103' },
      { name: '104' },
      { name: '105' },
      { name: '106' },
      { name: '107' },
      { name: '108' },
      { name: '109' },
      { name: '110' },
      {
        name: '111',
        type: 'service',
        alt_name_en: 'Graduate Student Association',
        alt_name_fr: 'Association des étudiants diplômés',
      },
      { name: '112' },
      { name: '113', type: 'test', },
      { name: '114' },
      { name: '115' },
      { name: '116', type: 'storage', },
      {
        name: '117',
        type: 'service',
        alt_name_en: 'Language Testing Services',
        alt_name_fr: 'Services d\'evaluation linguistique',
      },
      { name: '118' },
      { name: '119', type: 'storage', },
      { name: '120' },
      { name: '121' },
      { name: '122' },
      { name: '123' },
      { name: '124' },
      { name: '125' },
      { name: '126' },
      { name: '127' },
      {
        name: '130',
        type: 'service',
        alt_name_en: 'OLBI',
        alt_name_fr: 'ILOB',
      },
      { name: '131' },
      { name: '133' },
      { name: '134' },
      { name: '135' },
      { name: '136' },
      { name: '137' },
      { name: '138' },
      { name: '139' },
      { name: '140', type: 'test', },
      { name: '141' },
      { name: '142', type: 'kitchen', },
      { name: '143' },
      { name: '144' },
      { name: '145', type: 'meet', },
      { name: '201' },
      { name: '202' },
      { name: '203' },
      { name: '204' },
      { name: '205' },
      { name: '206' },
      { name: '207' },
      { name: '208' },
      { name: '210' },
      { name: '211' },
      { name: '212' },
      { name: '213' },
      {
        name: '215',
        type: 'seminar',
        alt_name_en: 'Scotiabank Room',
        alt_name_fr: 'Salle Banque Scotia',
      },
      { name: '216' },
      { name: '217' },
      { name: '218' },
      { name: '219' },
      { name: '220' },
      { name: '221' },
      { name: '222' },
      { name: '223' },
      { name: '224' },
      { name: '225' },
      { name: '227' },
      { name: '228' },
      { name: '229' },
      { name: '231' },
      { name: '232' },
      { name: '233', type: 'kitchen', },
      {
        name: '234',
        type: 'service',
        alt_name_en: 'Modern Languages and Literature Secretariat',
        alt_name_fr: 'Sécretariat des langues et littératures modernes',
      },
      { name: '235' },
      { name: '236' },
      { name: '237' },
      { name: '238' },
      { name: '239' },
      { name: '240' },
      { name: '241' },
      { name: '242' },
      { name: '243' },
      { name: '244' },
      { name: '245' },
      { name: '246', type: 'meet', },
      { name: '247' },
      { name: '248' },
      { name: '249' },
      { name: '250' },
      { name: '251' },
      { name: '252' },
      { name: '253' },
      { name: '257', type: 'class', },
      { name: '301', type: 'meet', },
      { name: '302' },
      { name: '303' },
      { name: '304' },
      { name: '305' },
      { name: '306' },
      { name: '307' },
      { name: '308' },
      { name: '309' },
      { name: '310' },
      { name: '311' },
      { name: '313' },
      { name: '314' },
      { name: '315' },
      { name: '316' },
      {
        name: '318',
        type: 'seminar',
        alt_name_en: 'Metropolitan Life Room',
        alt_name_fr: 'Salle La Métropolitaine',
      },
      { name: '319' },
      { name: '320' },
      {
        name: '321',
        type: 'service',
        alt_name: 'Undergraduate English Students\' Association',
      },
      { name: '322' },
      { name: '323' },
      { name: '324' },
      { name: '325' },
      { name: '326' },
      { name: '327' },
      { name: '328' },
      { name: '329' },
      { name: '330' },
      { name: '332' },
      { name: '334' },
      { name: '335' },
      { name: '336' },
      { name: '337' },
      {
        name: '338',
        type: 'service',
        alt_name_en: 'English Secretariat',
        alt_name_fr: 'Sécretariat des anglais',
      },
      { name: '339' },
      { name: '340' },
      { name: '341' },
      { name: '342' },
      { name: '343' },
      { name: '344' },
      { name: '345' },
      { name: '346' },
      { name: '347' },
      { name: '348' },
      { name: '349' },
      { name: '350', type: 'seminar', },
      { name: '351' },
      { name: '352' },
      { name: '353' },
      { name: '354' },
      { name: '355' },
      { name: '356' },
      {
        name: '401',
        type: 'service',
        alt_name_en: 'Linguistics, Translation and Interpretation Secretariat',
        alt_name_fr: 'Sécretariat des linguistique, traduction et interprétation',
      },
      { name: '402' },
      { name: '403' },
      { name: '404' },
      { name: '405' },
      { name: '406' },
      { name: '407' },
      { name: '408' },
      { name: '409' },
      { name: '410' },
      { name: '411' },
      { name: '412' },
      { name: '413' },
      { name: '415' },
      { name: '416' },
      { name: '417' },
      { name: '418' },
      {
        name: '420',
        type: 'seminar',
        alt_name_en: 'CIBC Room',
        alt_name_fr: 'Salle CIBC',
      },
      { name: '421' },
      { name: '422' },
      { name: '423' },
      { name: '424' },
      { name: '425' },
      { name: '426' },
      { name: '428' },
      { name: '429' },
      { name: '430' },
      { name: '432' },
      { name: '433' },
      { name: '434' },
      { name: '435' },
      {
        name: '436',
        type: 'meet',
        alt_name_en: 'Salon Monet Room',
        alt_name_fr: 'Salle Salon Monet',
      },
      { name: '437' },
      { name: '438' },
      { name: '439' },
      { name: '440' },
      { name: '441' },
      { name: '442' },
      { name: '443' },
      { name: '444' },
      { name: '445' },
      { name: '446' },
      { name: '447' },
      { name: '448' },
      { name: '449' },
      { name: '450' },
      { name: '451' },
      { name: '452' },
      {
        name: '501',
        type: 'service',
        alt_name_en: 'Digital Humanities',
        alt_name_fr: 'Sciences humaines numériques',
      },
      { name: '502' },
      { name: '503' },
      { name: '504' },
      { name: '505' },
      {
        name: '506',
        type: 'meet',
        alt_name_en: 'Brian Harris Room',
        alt_name_fr: 'Salle Brian Harris',
      },
      { name: '507' },
      { name: '509', type: 'meet', },
      { name: '511' },
      { name: '513', type: 'bath_uni', },
      { name: '515' },
      { name: '516' },
      { name: '517' },
      { name: '518' },
      { name: '519' },
      { name: '520' },
      { name: '521' },
      { name: '522' },
      { name: '523', type: 'seminar', },
      { name: '524' },
      { name: '525' },
      {
        name: '526',
        type: 'service',
        alt_name_en: 'Faculty of Arts Writing Centre',
        alt_name_fr: 'Centre d\'écriture de la faculté des arts',
      },
      { name: '527' },
      { name: '528' },
      { name: '529' },
      { name: '530' },
      { name: '531' },
    ],
  },

  {
    shorthand: 'MNO',
    image: require('../images/buildings/MNO.jpg'),
    name_en: 'Minto Sports Complex',
    name_fr: 'Complexe sportif Minto',
    location: {
      lat: 45.419746,
      long: -75.677470,
    },
    address_en: '801 King Edward Avenue',
    address_fr: '801, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MNT',
    image: require('../images/buildings/MNT.jpg'),
    name_en: 'Montpetit Hall',
    name_fr: 'Pavillon Montpetit',
    location: {
      lat: 45.422627,
      long: -75.682164,
    },
    address_en: '125 University Private',
    address_fr: '125, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRD',
    image: require('../images/buildings/MRD.jpg'),
    name_en: 'Marchand Residence',
    name_fr: 'Résidence Marchand',
    location: {
      lat: 45.422398,
      long: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRN',
    image: require('../images/buildings/MRN.jpg'),
    name_en: 'Marion Hall',
    name_fr: 'Pavillon Marion',
    location: {
      lat: 45.420643,
      long: -75.680979,
    },
    address_en: '140 Louis Pasteur Private',
    address_fr: '140, rue Louis Pasteur',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'MRT',
    image: require('../images/buildings/MRT.jpg'),
    name_en: 'Morisset Hall',
    name_fr: 'Pavillon Morisset',
    location: {
      lat: 45.423232,
      long: -75.684163,
    },
    address_en: '65 University Private',
    address_fr: '65, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'PRZ',
    image: require('../images/buildings/PRZ.jpg'),
    name_en: 'Pérez Hall',
    name_fr: 'Pavillon Pérez',
    location: {
      lat: 45.423789,
      long: -75.684767,
    },
    address_en: '50 University Private',
    address_fr: '50, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SCR',
    image: require('../images/buildings/SCR.jpg'),
    name: 'Sacré-Coeur',
    location: {
      lat: 45.423824,
      long: -75.684096,
    },
    address_en: '591 Cumberland Street',
    address_fr: '591, rue Cumberland',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SCS',
    image: require('../images/buildings/MNO.jpg'),
    name_en: 'Minto Sports Complex',
    name_fr: 'Complexe sportif Minto',
    location: {
      lat: 45.419746,
      long: -75.677470,
    },
    address_en: '801 King Edward Avenue',
    address_fr: '801, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SMD',
    image: require('../images/buildings/SMD.jpg'),
    name_en: 'Simard Hall',
    name_fr: 'Pavillon Simard',
    location: {
      lat: 45.423215,
      long: -75.685737,
    },
    address_en: '60 University Private',
    address_fr: '60, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SMN',
    image: require('../images/buildings/SMN.jpg'),
    name_en: 'Academic Hall',
    name_fr: 'Salle académique',
    location: {
      lat: 45.425135,
      long: -75.686424,
    },
    address_en: '133/135 Séraphin Marion Private',
    address_fr: '133/135, rue Séraphin Marion',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STE',
    image: require('../images/buildings/STE.jpg'),
    name: 'SITE',
    location: {
      lat: 45.419359,
      long: -75.678692,
    },
    address_en: '800 King Edward Avenue',
    address_fr: '800, avenue King Edward',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STN',
    image: require('../images/buildings/STN.jpg'),
    name_en: 'Stanton Residence',
    name_fr: 'Résidence Stanton',
    location: {
      lat: 45.422398,
      long: -75.684454,
    },
    address_en: '90 University Private',
    address_fr: '90, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'STT',
    image: require('../images/buildings/STT.jpg'),
    name: '1 Stewart',
    location: {
      lat: 45.425652,
      long: -75.687365,
    },
    address_en: '1 Stewart Street',
    address_fr: '1, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'SWT',
    image: require('../images/buildings/SWT.jpg'),
    name_en: 'Centre for Academic Leadership',
    name_fr: 'Centre de leadership scolaire',
    location: {
      lat: 45.425853,
      long: -75.686582,
    },
    address_en: '30/32 Stewart Street',
    address_fr: '30/32, rue Stewart',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'TBT',
    image: require('../images/buildings/TBT.jpg'),
    name_en: 'Tabaret Hall',
    name_fr: 'Pavillon Tabaret',
    location: {
      lat: 45.424683,
      long: -75.685877,
    },
    address_en: '550 Cumberland Street',
    address_fr: '550, rue Cumberland',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'THN',
    image: require('../images/buildings/THN.jpg'),
    name_en: 'Thompson Residence',
    name_fr: 'Résidence Thompson',
    location: {
      lat: 45.424130,
      long: -75.683206,
    },
    address_en: '25 University Private',
    address_fr: '25, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'UCU',
    image: require('../images/buildings/UCU.jpg'),
    name_en: 'Jock-Turcot University Centre',
    name_fr: 'Centre universitaire Jock-Turcot',
    location: {
      lat: 45.422557,
      long: -75.683307,
    },
    address_en: '85 University Private',
    address_fr: '85, rue University',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'VNR',
    image: require('../images/buildings/VNR.jpg'),
    name_en: 'Vanier Hall',
    name_fr: 'Pavillon Vanier',
    location: {
      lat: 45.421487,
      long: -75.683413,
    },
    address_en: '136 Jean-Jacques Lussier Private',
    address_fr: '136, rue Jean-Jacques Lussier',
    facilities: [],
    rooms: [],
  },

  {
    shorthand: 'WLD',
    image: require('../images/buildings/WLD.jpg'),
    name: 'Wilbrod',
    location: {
      lat: 45.426043,
      long: -75.684203,
    },
    address_en: '200 Wilbrod Street',
    address_fr: '200, rue Wilbrod',
    facilities: [],
    rooms: [],
  },

];
